### ISSUE TITLE
r2taint is not working with corefiles

### ISSUE THREAD

**Issue by s0i37** [BinaryAnalysisPlatform/bap#1260] opened 2020-12-14 20:22 UTC
Hello.
Does BAP support analysis corefile and minidump?
If not, will it support in future?
Thank you

**Comment by XVilka** [comment] 2020-12-15 00:17
Since both [Radare2](https://github.com/radareorg/radare2) and [Rizin](https://github.com/rizinorg/rizin) support loading both, including various Windows minidump formats - it might be an option to use the already existing integration that is already in the BAP.

**Comment by s0i37** [comment] 2020-12-15 07:15
I know about radare2. But I asked how to do the same with BAP) I tried to run analysis for corefile but didn't return any result.

**Comment by XVilka** [comment] 2020-12-15 08:09
Yes, I understand - I just though the loading feature might be implemented in this plugin [`plugins/radare2](https://github.com/BinaryAnalysisPlatform/bap/tree/master/plugins/radare2)

**Comment by s0i37** [comment] 2020-12-15 10:29
I know. Originally a came here from this issue  https://github.com/0xchase/r2taint/issues/1 ))

**Comment by ivg** [comment] 2021-01-05 22:07
Yes, we were planning to implement it for nearly five years (in fact your issue is a duplicate of #491) but we never had time to even start working on it. With that said, we already should be able to at least load and analyze the core file and you should be getting some results. What will be missing is that the state will not be initialized (that is what #491 is about). So it could be that some of the options (like the rather arbitrary `-llvm-base=0x400000-llvm-base=0x400000`) that r2taint is passing are breaking the analysis. So it might be that the issue is still on the r2taint size :) 

Besides, I would be happy to explain how to implement `r2taint` more efficiently and much easier. We even have python code that does the same for IDA Pro, so you can adapt it to radare2.

**Comment by ivg** [comment] 2021-04-30 20:24
You're very welcome to drop by our Gitter [channel][1] if you have any questions or need help with this issue.

[1]: https://gitter.im/BinaryAnalysisPlatform/bap

**Closed by ivg** 2021-04-30 20:24 UTC
