### ISSUE TITLE
[bap-llvm] TargetInstrInfo.h moved

### ISSUE THREAD

**Issue by tobast** [BinaryAnalysisPlatform/bap#883] opened 2018-10-05 10:32 UTC
Hello,

The header file `llvm/Target/TargetInstrInfo.h`, mentioned as of b4ecb65ea [in `llvm_disasm.cpp` line 13](https://github.com/BinaryAnalysisPlatform/bap/blob/b4ecb65eafb318e885541be0c3602e73f1e6519e/lib/bap_llvm/llvm_disasm.cpp#L13), has been moved by commit llvm-mirror/llvm@48319238e40440d4a153ba057e8f1292a73767f4 to `llvm/CodeGen/TargetInstrInfo.h`. This causes `bap-llvm` to fail upon compilation, for instance when one tries to `opam install bap`.

**Comment by ivg** [comment] 2018-10-05 12:19
It's duplicate of #877, and is fixed half a year ago in 1.5. 

Workarounds:
1. install LLVM 5.0 (or earlier version)
2. install bap 1.5 from the testing repository
3. wait until bap 1.5 is merged in the upstream opam repository

**Closed by ivg** 2018-10-05 12:19 UTC
