### ISSUE TITLE
Translate x86 instructions to BAP IR

### ISSUE THREAD

**Issue by computereasy** [BinaryAnalysisPlatform/bap#251] opened 2015-06-23 00:07 UTC
Hello everyone,

Here is a quick question: suppose I have had a sequence of instructions recovered from binaries. And I want to translate to BAP IR. 

Something like this:

    List.map (fun i : String -> Bap.trans i) instrs  

Can BAP support this? Or if not, I might try to work on it...

Thank you!

**Comment by ivg** [comment] 2015-06-23 01:47
If I understand you correctly, then it can. There are (from top to down):
- [Program.lift](http://binaryanalysisplatform.github.io/bap/api/master/Bap.Std.Program.html#VALlift) – will lift a whole program to IR;
- [Sub.lift](http://binaryanalysisplatform.github.io/bap/api/master/Bap.Std.Sub.html#VALlift) – will lift a binary symbol into a subroutine;
- [Blk.lift](http://binaryanalysisplatform.github.io/bap/api/master/Bap.Std.Blk.html#VALlift) – to lift a machine basic block to a sequence of IR block;

Also, program is automatically transformed into an IR, without any special requirement. So, for example, if you've registered your function using a plugin infrastructure, or just initialized a project yourself, then an IR of the program can be accessed with `Project.program` functions.

Anyway, thanks for trying to help, I really appreciate it.

**Comment by ivg** [comment] 2015-06-23 02:14
And if you were talking about raw bytes, then you might be interested in `bap-mc` tool. It can take raw bytes, and disassemble them on per instruction base:

```sh
$ bap-mc  "\x48\x83\xec\x08" --show-bir --show-insn
subq $0x8, %rsp
00000001: 
00000002: t_1 := RSP
00000003: RSP := RSP - 0x8:64
00000004: CF := t_1 < 0x8:64
00000005: OF := high:1[(t_1 ^ 0x8:64) & (t_1 ^ RSP)]
00000006: AF := (((RSP ^ t_1) ^ 0x8:64) & 0x10:64) = 0x10:64
00000007: PF := ~(low:1[let acc_2 = (RSP >> 0x4:64) ^ RSP in
                  let acc_2 = (acc_2 >> 0x2:64) ^ acc_2 in (acc_2 >> 0x1:64) ^ acc_2])
00000008: SF := high:1[RSP]
00000009: ZF := RSP = 0x0:64
```

**Comment by computereasy** [comment] 2015-06-23 02:19
Hi @ivg, I really appreciate your kind response. Let me try to elaborate it a little bit.

Here is some instructions in the `String` representation.

    let il = ["mov $0x01, %eax", "push %eax", "pop %ebx"]

These instructions have been recovered from binaries, and I don't need the disassembly infrastructure of `BAP`. 

What I want to do, is translate these string representations into BAP IR. It can be IR in strings, or parsed data structure, they are both fine to me.

   let bap_ir : string list =  List.map (fun i : string -> Bap.trans i) il
   
or 
   let bap_ir : ir list = List.map (fun i : string -> Bap.trans i) il

Can `BAP` support a function , or some combinations of functions like `Bap.trans` in the above case?

**Comment by ivg** [comment] 2015-06-23 10:53
Nope, bap doesn't contain assembler, only a disassembler. In order for your example to work, you need at first to assemble instruction back into machine code. 

Just in case you didn't know, bap can disassemble not only into IR, but to BIL (Bap Instruction Language), Target assembly, and llvm machine code. Look at -dbil and -dasm options of bap utility.

**Comment by computereasy** [comment] 2015-06-23 13:43
@ivg , thank you ivg. I tried `-dbil` and `-dir`. But could you tell me where is the `llvm` machine code translator?

**Comment by ivg** [comment] 2015-06-23 13:56
You should try `-dasm`. A sample output is on our [README](https://github.com/BinaryAnalysisPlatform/bap#using-from-shell). For example, 
```
0000a008: 00 b0 8d e2    add r11, sp, #0x0   ; ADDri(R11,SP,0x0,0xe,Nil,Nil)
```
The string to the right of `;` is an LLVM machine code. 

But of course, bap is a library first of all. So, if you do want to do something with LLVM machine code, you can take a look at `insn` type. Look at our [disassembler](http://binaryanalysisplatform.github.io/bap/api/master/Bap.Std.html#disasm) library.

**Comment by computereasy** [comment] 2015-06-23 15:42
@ivg , thank you for your response. I am sorry for another stupid question.. I can use `bap-mc` to generate BIL in `json` format. But it seems to me that `bap-mc` only takes raw hex sequence as input.. So I am wondering is there any functionality in `bap` that can support BIL output in `json` format with a binary as input..? 

Really sorry if I trouble you too much...

**Comment by ivg** [comment] 2015-06-23 16:49
Currently, `bap-mc` doesn't support reading raw binary strings. Only ASCII strings, escaped in different formats. This is because, this utility is mostly used in user interaction, c.f., `llvm-mc`. 

There is no fundamental problem in adding this functionality to `bap-mc`. But I don't think that it is needed. `bap-mc` is just a tool, and if you need to work with real binary information, it looks like that you need to use library. 

If you would like to stay high-level, then you can use [`Project.from_string`][1]. It will return all information, including IR, BIL, ASM, LLVM, CFG, and other fancy acronyms =)

For example, run `baptop` and start playing:
```ocaml
# let proj = ok_exn (Project.from_string `x86 "\x48\x83\xec\x08");;
# Project.program proj;;
# Project.program proj;;
- : Bap.Std.program Bap.Std.term = 00000024: program
00000023: sub sub_0()
00000013: 
00000014: t_13 := low:32[EAX]
00000015: EAX := (low:32[EAX]) - 0x1:32
00000016: OF := high:1[(t_13 ^ 0x1:32) & (t_13 ^ (low:32[EAX]))]
00000017: AF := ((((low:32[EAX]) ^ t_13) ^ 0x1:32) & 0x10:32) = 0x10:32
00000018: PF := ~(low:1[let acc_14 = ((low:32[EAX]) >> 0x4:32) ^ (low:32[EAX]) in
let acc_14 = (acc_14 >> 0x2:32) ^ acc_14 in (acc_14 >> 0x1:32) ^ acc_14])
00000019: SF := high:1[low:32[EAX]]
0000001a: ZF := (low:32[EAX]) = 0x0:32
0000001b: t_15 := low:32[ESP]
0000001c: ESP := (low:32[ESP]) - 0x8:32
0000001d: CF := t_15 < 0x8:32
0000001e: OF := high:1[(t_15 ^ 0x8:32) & (t_15 ^ (low:32[ESP]))]
0000001f: AF := ((((low:32[ESP]) ^ t_15) ^ 0x8:32) & 0x10:32) = 0x10:32
00000020: PF := ~(low:1[let acc_16 = ((low:32[ESP]) >> 0x4:32) ^ (low:32[ESP]) in
let acc_16 = (acc_16 >> 0x2:32) ^ acc_16 in (acc_16 >> 0x1:32) ^ acc_16])
00000021: SF := high:1[low:32[ESP]]
00000022: ZF := (low:32[ESP]) = 0x0:32

# Project.disasm proj |> Disasm.insns |> Seq.to_list;;
- : (Bap.Std.mem * Bap.Std.insn) list =
[(00000000: 48 , decl %eax; DEC32r(EAX,EAX));
 (00000001: 83 ec 08 , subl $0x8, %esp; SUB32ri8(ESP,ESP,0x8))]


# Project.disasm proj |> Disasm.insns |> Seq.map ~f:snd |> Seq.map ~f:Insn.bil |> Seq.to_list;;
- : Bap.Std.bil list =
[{
   t_13 := low:32[EAX]
   EAX := (low:32[EAX]) - 0x1:32
   OF := high:1[(t_13 ^ 0x1:32) & (t_13 ^ (low:32[EAX]))]
   AF := 0x10:32 = (0x10:32 & (((low:32[EAX]) ^ t_13) ^ 0x1:32))
   PF := ~(low:1[let acc_14 = ((low:32[EAX]) >> 0x4:32) ^ (low:32[EAX]) in
     let acc_14 = (acc_14 >> 0x2:32) ^ acc_14 in
     (acc_14 >> 0x1:32) ^ acc_14])
   SF := high:1[low:32[EAX]]
   ZF := 0x0:32 = (low:32[EAX])
 };
 {
   t_15 := low:32[ESP]
   ESP := (low:32[ESP]) - 0x8:32
   CF := t_15 < 0x8:32
   OF := high:1[(t_15 ^ 0x8:32) & (t_15 ^ (low:32[ESP]))]
   AF := 0x10:32 = (0x10:32 & (((low:32[ESP]) ^ t_15) ^ 0x8:32))
   PF := ~(low:1[let acc_16 = ((low:32[ESP]) >> 0x4:32) ^ (low:32[ESP]) in
     let acc_16 = (acc_16 >> 0x2:32) ^ acc_16 in
     (acc_16 >> 0x1:32) ^ acc_16])
   SF := high:1[low:32[ESP]]
   ZF := 0x0:32 = (low:32[ESP])
 }]
# 
```


> Really sorry if I trouble you too much...

You're not troubling at all :)


[1]: http://binaryanalysisplatform.github.io/bap/api/v0.9.8/Bap.Std.Project.html#VALfrom_string

**Comment by computereasy** [comment] 2015-06-23 18:51
@ivg , thank you for your nice response. I am thinking to translate `bil` type, which is basically `stmt list` type into its `json` representation. I found that in the implementation of `bap-mc`, the `bil_piqi` module is used with `json_of_stmts` function, to print `stmt` to `json` string. 

I tried in the `baptop` this way:

    # #require "bap.types";;
    # open Bil_piqi;;

It works fine. However, when I did this:

    # Bil_piqi.json_of_stmts;;
   Error: Reference to undefined global `Bil_piqi' 

I might again make something wrong.. Is there any chance that you can shed light on it..?  Thank you for your time and I really appreciate that!

**Comment by KennethAdamMiller** [comment] 2015-06-23 19:18
#require "bap";;
open Bap.Std

Bil_piqi.json_of_stmts

^  has worked for me in the past

**Comment by ivg** [comment] 2015-06-23 19:48
To load piqi library, you should use 
```
# #require "bap.serialization";;
```

But the problem is that it will not work, due to an [issue][1] in a piqi library, that is responsible for serialization:
```
Error: The external function `camlidl_piqi_c_piqi_strtoull' is not available
```

That also means, that you can't use in a plugin. Since it is also linked dynamically. But, you can still compile a standalone application, using it. You can compile it with:
```
ocamlbuild -pkg bap -pkg bap.serialization yourfilename.native
```
Assuming, that your code is in `yourfilename.ml`.

Are you trying to call Bap from some other language?  And why do you want to work with BIL? It is better to work with IR, rather than with abstract syntax tree. 

[1]: https://github.com/alavrik/piqi/issues/50

**Comment by KennethAdamMiller** [comment] 2015-06-23 19:59
I fixed that specific error and shipped the error a long time ago. I even
merged in the changes to piqi in order to fix that. Possibly the bap piqi
dependency version spec hasn't been updated? Is that specific error still
cropping up?

**Comment by ivg** [comment] 2015-06-23 20:01
@KennethAdamMiller, I've tested with piqi 0.7.4 and 0.7.1. This are the latest available versions in opam so far.

**Comment by KennethAdamMiller** [comment] 2015-06-23 20:17
Ah I'm really sorry about that. I don't know how that slipped in, because I
tried my best to test everything and ship changes that were ensured to
work. Possibly the piqi on github is sitting at a more recent version than
the piqi version that opam associates to, eg a commit in piqi, but opam
version is pointed a different commit. I will go and search the issue
trackers and my conversation with the maintainer and see if I can't get a
fix for that out quickly.

**Comment by ivg** [comment] 2015-06-23 20:31
@KennethAdamMiller, indeed. The change didn't came up into `opam`:
```
$ opam source piqilib
$ less piqilib.0.6.12/piqilib/Makefile | grep STATIC
STATIC = 1 # force creation of static library (don't create dlls)
```

**Closed** 2015-07-21 15:57 UTC
