### ISSUE TITLE
Bap installation fails

### ISSUE THREAD

**Issue by sborpo** [BinaryAnalysisPlatform/bap#552] opened 2016-09-15 10:00 UTC
Hello,
I have tried to install BAP following the instuctions on the main git page
running the last command (opam install bap) doesn't seems to work for me :( - 
it produces error - i pasted it below.
I'm rarely using linux , so i having difficluties to understand what is the problem.

Will be glad to get some help , thanks!

```

=-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
∗  installed conf-m4.1
∗  installed conf-gmp.1
∗  installed conf-pkg-config.1.0
∗  installed conf-ncurses.1
∗  installed conf-which.1
∗  installed result.1.2
∗  installed ocamlfind.1.6.2
∗  installed base-bytes.base
∗  installed camlzip.1.06
∗  installed base64.2.0.0
∗  installed cppo.1.4.0
∗  installed easy-format.1.2.0
∗  installed ocamlify.0.0.1
∗  installed ocamlmod.0.0.8
∗  installed ocamlgraph.1.8.7
∗  installed ocplib-endian.1.0
∗  installed ounit.2.0.0
∗  installed ppx_tools.5.0+4.02.0
∗  installed fileutils.0.4.4
∗  installed re.1.6.1
∗  installed react.1.2.0
∗  installed stringext.1.4.2
∗  installed camomile.0.8.5
∗  installed uutf.0.9.4
∗  installed topkg.0.7.8
∗  installed uuidm.0.9.6
∗  installed xmlm.1.2.0
∗  installed jsonm.0.9.1
∗  installed zarith.1.2
∗  installed zed.1.4
∗  installed oasis.0.4.7
∗  installed camlp4.4.02+7
∗  installed herelib.112.35.00
∗  installed faillib.111.17.00
∗  installed optcomp.1.6
∗  installed pipebang.110.01.00
∗  installed bitstring.2.0.4
∗  installed ulex.1.1
∗  installed type_conv.112.01.02
∗  installed comparelib.109.60.00
∗  installed enumerate.111.08.00
∗  installed bin_prot.112.35.00
∗  installed fieldslib.109.20.03
∗  installed pa_ounit.112.35.00
∗  installed piqilib.0.6.13
∗  installed pa_bench.112.06.00
∗  installed piqi.0.7.5
∗  installed lwt.2.4.8
∗  installed variantslib.109.15.03
∗  installed sexplib.112.35.00
∗  installed custom_printf.112.24.00
∗  installed cstruct.1.9.0
∗  installed ipaddr.2.6.1
∗  installed hex.1.0.0
∗  installed pa_test.112.24.00
∗  installed lambda-term.1.10.1
∗  installed ezjsonm.0.4.3
∗  installed typerep.112.35.00
∗  installed utop.1.19.3
∗  installed uri.1.9.1
∗  installed conduit.0.9.0
∗  installed ocurl.0.7.1
∗  installed cohttp.0.15.2
∗  installed core_kernel.112.35.00
[ERROR] The compilation of bap failed at "make".
Processing 65/65: [bap: rm]
#=== ERROR while installing bap.0.9.9 =========================================#
# opam-version 1.2.2
# os           linux
# command      make
# path         /home/guest/.opam/4.02.1/build/bap.0.9.9
# compiler     4.02.1
# exit-code    2
# env-file     /home/guest/.opam/4.02.1/build/bap.0.9.9/bap-14516-cb3985.env
# stdout-file  /home/guest/.opam/4.02.1/build/bap.0.9.9/bap-14516-cb3985.out
# stderr-file  /home/guest/.opam/4.02.1/build/bap.0.9.9/bap-14516-cb3985.err
### stdout ###
# ocaml setup.ml -quiet -build 
# /home/guest/.opam/4.02.1/bin/ocamlopt.opt unix.cmxa -I /home/guest/.opam/4.02.1/lib/ocaml/ocamlbuild /home/guest/.opam/4.02.1/lib/ocaml/ocamlbuild/ocamlbuildlib.cmxa myocamlbuild.ml /home/guest/.opam/4.02.1/lib/ocaml/ocamlbuild/ocamlbuild.cmx -o myocamlbuild
# + /home/guest/.opam/4.02.1/bin/ocamlopt.opt unix.cmxa -I /home/guest/.opam/4.02.1/lib/ocaml/ocamlbuild /home/guest/.opam/4.02.1/lib/ocaml/ocamlbuild/ocamlbuildlib.cmxa myocamlbuild.ml /home/guest/.opam/4.02.1/lib/ocaml/ocamlbuild/ocamlbuild.cmx -o myocamlbuild
# File "myocamlbuild.ml", line 1020, characters 14-43:
# Error: Unbound value MyOCamlbuildBase.env_filename
# Command exited with code 2.
### stderr ###
# make: *** [build] Error 1



=-=- Error report -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
The following actions failed
  ∗  install bap 0.9.9
The following changes have been performed
  ∗  install base-bytes      base      
  ∗  install base64          2.0.0     
  ∗  install bin_prot        112.35.00 
  ∗  install bitstring       2.0.4     
  ∗  install camlp4          4.02+7    
  ∗  install camlzip         1.06      
  ∗  install camomile        0.8.5     
  ∗  install cohttp          0.15.2    
  ∗  install comparelib      109.60.00 
  ∗  install conduit         0.9.0     
  ∗  install conf-gmp        1         
  ∗  install conf-m4         1         
  ∗  install conf-ncurses    1         
  ∗  install conf-pkg-config 1.0       
  ∗  install conf-which      1         
  ∗  install core_kernel     112.35.00 
  ∗  install cppo            1.4.0     
  ∗  install cstruct         1.9.0     
  ∗  install custom_printf   112.24.00 
  ∗  install easy-format     1.2.0     
  ∗  install enumerate       111.08.00 
  ∗  install ezjsonm         0.4.3     
  ∗  install faillib         111.17.00 
  ∗  install fieldslib       109.20.03 
  ∗  install fileutils       0.4.4     
  ∗  install herelib         112.35.00 
  ∗  install hex             1.0.0     
  ∗  install ipaddr          2.6.1     
  ∗  install jsonm           0.9.1     
  ∗  install lambda-term     1.10.1    
  ∗  install lwt             2.4.8     
  ∗  install oasis           0.4.7     
  ∗  install ocamlfind       1.6.2     
  ∗  install ocamlgraph      1.8.7     
  ∗  install ocamlify        0.0.1     
  ∗  install ocamlmod        0.0.8     
  ∗  install ocplib-endian   1.0       
  ∗  install ocurl           0.7.1     
  ∗  install optcomp         1.6       
  ∗  install ounit           2.0.0     
  ∗  install pa_bench        112.06.00 
  ∗  install pa_ounit        112.35.00 
  ∗  install pa_test         112.24.00 
  ∗  install pipebang        110.01.00 
  ∗  install piqi            0.7.5     
  ∗  install piqilib         0.6.13    
  ∗  install ppx_tools       5.0+4.02.0
  ∗  install re              1.6.1     
  ∗  install react           1.2.0     
  ∗  install result          1.2       
  ∗  install sexplib         112.35.00 
  ∗  install stringext       1.4.2     
  ∗  install topkg           0.7.8     
  ∗  install type_conv       112.01.02 
  ∗  install typerep         112.35.00 
  ∗  install ulex            1.1       
  ∗  install uri             1.9.1     
  ∗  install utop            1.19.3    
  ∗  install uuidm           0.9.6     
  ∗  install uutf            0.9.4     
  ∗  install variantslib     109.15.03 
  ∗  install xmlm            1.2.0     
  ∗  install zarith          1.2       
  ∗  install zed             1.4       

=-=- bap.0.9.9 troobleshooting =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
=> This package relies on external (system) dependencies that may be missing.
   `opam depext bap.0.9.9' may help you find the correct installation for your
   system.

The former state can be restored with:
    opam switch import "~/.opam/4.02.1/backup/state-20160815083703.export"
```

**Comment by ivg** [comment] 2016-09-15 11:45
Yeah, this is a known issue. `oasis.0.4.7` package has introduced breaking changes. The issue is already resolved in the upstream repository, but is not yet pushed to the ocaml.org. I would suggest you to switch to the upstream repository:

```
opam repo add git://github.com/BinaryAnalysisPlatform/opam-repository.git
```

Then you can safely install the latest bap:

```
opam install bap
```

**Comment by sborpo** [comment] 2016-09-15 12:43
Thanks for the help,
I executed the commands and got a message about the oasis package ,
shouldn't it get downgraded ? 


```
guest@Ubuntux86:~$ opam repository add bap git://github.com/BinaryAnalysisPlatform/opam-repository.git
[bap] git://github.com/BinaryAnalysisPlatform/opam-repository.git updated
guest@Ubuntux86:~$ opam install bap
The following dependencies couldn't be met:
  - bap -> oasis < 0.4.7
Your request can't be satisfied:
  - No package matches oasis<0.4.7.

No solution found, exiting
guest@Ubuntux86:~$ 
```

**Comment by ivg** [comment] 2016-09-15 12:44
hmm... sounds strange, can you try this command:

```
opam install bap.1.0.0~alpha
```

**Comment by sborpo** [comment] 2016-09-15 12:47
Something is wrong with my configurations ?

```
guest@Ubuntux86:~$ opam install bap.1.0.0~alpha
Your request can't be satisfied:
  - No package matches bap.1.0.0~alpha.

No solution found, exiting

```

**Comment by ivg** [comment] 2016-09-15 12:51
Ok, so it looks like, that opam entered some overcomplicated state, after it partially installed bap, and it can't resolve it correctly (maybe you don't have aspcud installed). The [oasis.0.4.6][1] definitely should satisfy the dependency. The 1.0.0~alpha version is not available, because your compiler version is to old. So, I would suggest to switch to a newer compiler (it will also create a fresh switch), and install the latest bap:

```
opam switch 4.02.3
eval `opam config env`
opam install bap
```

[1]: https://opam.ocaml.org/packages/oasis/oasis.0.4.6/

**Comment by sborpo** [comment] 2016-09-15 13:17
Worked for me , **Thanks alot!!!!**
By the way, my goal is to run the byteweight module using BAP,
i'm unfamiliar with OCaml , do you have a reference to simple code snippets that let me run byteweight on a certain file ?

**Comment by ivg** [comment] 2016-09-15 13:26
It depends on what do you want to do with byteweight. We have `bap-byteweight` toolkit, that is a swiss-knife utility that can create signatures, train them on different binaries, and then test them. You can install it with `opam install bap-byteweight`. We also have a `bap-fsi-benchmark` (`opam install bap-fsi-benchmark) utility, to run the competitions between byteweight and other algorithms (e.g., ida flirt). Finally, we have a library. I would suggest to start with our [reference manual][1]. Everything noted above is documented there in detail.  Don't hesitate to ask questions if you got stuck somewhere :)

[1]: http://binaryanalysisplatform.github.io/bap/api/master/argot_index.html

**Comment by sborpo** [comment] 2016-09-15 13:42
Thanks again for the detailed explanation!

**Comment by sborpo** [comment] 2016-09-15 14:23
I read this issue:
https://github.com/BinaryAnalysisPlatform/binaryanalysisplatform.github.io/blob/master/_drafts/bap-fsi-benchmark.md

I tried to download the updated signatures using bap-byteweight update , but it writes me that the command not found.

(when i tried to install the byteweight opam install byteweight - it says that the package already installed)

**Closed** 2016-09-19 12:10 UTC
