### ISSUE TITLE
incorrect lifting of btc

### ISSUE THREAD

**Issue by rsinha** [BinaryAnalysisPlatform/bap#287] opened 2015-08-14 18:31 UTC
It seems that the Bil lifting of btc instruction only updates the CF flag, but does not complement the bit.
Here's an example with only 1 btc instruction.
```
echo 480FBAF81D | bap-mc --show-bil=bil
```

**Comment by ivg** [comment] 2015-08-14 19:33
Thanks for catching this. So, I did some investigation, it looks like the problem is that currently lifter supports only `bt` instruction. `bts`, `btc` and `btr` are not supported at all. And `btc` is sometimes confused with `bt`.  I will see, what can be done.

**Comment by ivg** [comment] 2015-08-18 19:26
Fixing this issue will require significant rewrite of the current lifter. I've started this as a [side project](https://github.com/ivg/x86-lifter), that will be merged into bap as soon as it will become mature enough.

**Closed** 2016-09-09 12:59 UTC
Labels: bug, x86-lifter
