### ISSUE TITLE
Modifying Saluki (or another plugin) to taint command line input

### ISSUE THREAD

**Issue by pragyansmita** [BinaryAnalysisPlatform/bap#703] opened 2017-09-07 19:25 UTC
Hello,

I was wondering if it is possible to taint the command line input to certain sinks and/or visually marking them for analyst review in IDA as saluki does.

My initial thought was to modify saluki's existing taint source/sink rule, but was unsure how to include command line input as a source:

let untrusted_input src sink =
  define ("TAINT/"^src^"_may_leak_into_"^sink) [
    rule ("if_there_is_data_dependency")
      [sub src[p]; sub sink[q]]
      [never]
  ] vars [reg *p; reg *q] such that [q/p;]

**Comment by ivg** [comment] 2017-09-12 03:39
First of all, you can taint manually by attaching the `Taint.ptr` or `Taint.reg` attributes to any attribute. 

Speaking of the main function arguments you can just taint the argument terms, and every time they are evaluated the taint will be introduced into the system. The main complication here is that in a general case, the extent of the arguments array is unknown and can be infinite, so a conservative tainting will eventually taint the whole stack.

**Comment by Dinatrix** [comment] 2017-09-12 17:51
We tried (and successfully built/installed) a new version of saluki utilizing the existing untrusted_input function with strrchr as the src (as it appears to operate on the command line input directly after it appears in the system in our malicious ls test case) and fopen64 as the sink.

When running the new saluki in IDA on the 'ls' that comes with ubuntu 16.04, we see it complete and know it is the newest saluki version as it contains the strrchr update:

![image2](https://user-images.githubusercontent.com/10760263/30340379-52669b4c-97c0-11e7-8f6a-327de3465c14.png)
(And doesn't find anything as this is a non-malicious ls) Yet, when we run the same plugin over a malicious ls.coreutils (where a command line trigger is able to launch a file, hence the search for untrusted input flowing to the fopen) the plugin errors out?:

![image](https://user-images.githubusercontent.com/10760263/30340371-4e247d7e-97c0-11e7-816c-ae948b070d1c.png)

The only difference I can think of is that the malicious ls.coreutils was ARM which may have caused an error? 

Additionally, when you say 'attaching the Taint.ptr or Taint.reg attributes to any attribute' do you mean within the saluki plugin itself?

**Comment by ivg** [comment] 2017-09-13 13:01
Ah, can you scroll up the backtrace a little bit, as I can't see the actual error? Or just copy the actual text if it is possible. 

> Additionally, when you say 'attaching the Taint.ptr or Taint.reg attributes to any attribute' do you mean within the saluki plugin itself?

In general yes, but in some cases you can use `taint` and `map-terms` plugins along with saluki predicates.

**Comment by Dinatrix** [comment] 2017-09-13 14:32
Unfortunately there doesn't seem to be much more information in the output window or bap tabs:
![image](https://user-images.githubusercontent.com/10760263/30382963-9725d9ec-986e-11e7-8f12-155099013fa2.png)
![image](https://user-images.githubusercontent.com/10760263/30383005-aa7c3946-986e-11e7-91d4-49d887883c7a.png)

**Comment by ivg** [comment] 2017-09-13 16:48
Are you using bap 1.3? It looks like that the error message is somehow overwritten or maybe it is somewhere on the right. Because there should be the error message itself.

**Comment by Dinatrix** [comment] 2017-09-13 17:32
Ah this is bap.1.2. We will try on bap.1.3 and report back

**Comment by Dinatrix** [comment] 2017-09-14 19:57
In a separate VM with bap 1.3.0 installed, I was unable to use the plugin (or any bap plugins) from within IDA.
It seems the current 'opam install bap.1.3.0' does not install bap-ida-python by default.
When I went to install bap-ida-python.1.3.0, there is only a 1.2.0 version which wants to downgrade the other bap components it requires to 1.1.0.
Looking at the bap-ida-python readme on github, I also tried copying all the files/directories from the bap plugins directory to my ida-6.95/plugins directory but was not prompted upon my next run of IDA for the BAP prompt as mentioned.

**Comment by ivg** [comment] 2017-09-14 20:01
The problem is that bap-ida-python wasn't released during the 1.3 release. This is an oversight. I will release it ASAP. 

Btw, `opam install bap` shouldn't install `bap-ida-python`, the latter should be always installed manually.

**Comment by ivg** [comment] 2017-09-14 20:10
On the other hand, the old `bap-ida-python.1.2` should still be installable with 1.3, e.g., on mine machine

```
$ opam show bap | grep version
             version: 1.3.0
   installed-version: 1.3.0 [system]
  available-versions: 0.9.1, 0.9.2, 0.9.3, 0.9.4, 0.9.5, 0.9.6, 0.9.7, 0.9.8, 0.9.9, 1.0.0, 1.1.0, 1.2.0, 1.3.0
```

```
 opam install bap-ida-python
The following actions will be performed:
  ∗  install conf-ida       0.1               [required by bap-ida-python]
  ∗  install bap-ida-python 1.2.0
===== ∗  2 =====
Do you want to continue ? [Y/n] y

=-=- Gathering sources =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Processing  2/2: [bap-ida-python: from default]
[default] https://opam.ocaml.org/archives/bap-ida-python.1.2.0+opam.tar.gz downloaded

=-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
∗  installed conf-ida.0.1
∗  installed bap-ida-python.1.2.0
Done.
```

But that's not to say, that I shouldn't release the new version. It will be ready soon (it may take some time, before it will land up in the official repo)

**Comment by ivg** [comment] 2017-09-14 20:18
> but was not prompted upon my next run of IDA for the BAP prompt as mentioned

The prompt is fired only if the path to bap is not set in the configuration file, e.g.,
```
$ cat ~/ida-6.9/cfg/bap.cfg 
.default
bap_executable_path    /home/ivg/.opam/system/bin/bap
```

Once it is set, it will be used. You can edit it manually though (there is no need to restart IDA after that, the configuraion file is consulted every time a plugin is run)

**Comment by Dinatrix** [comment] 2017-09-14 21:10
We attempted to install bap-ida-python by itself but have run into an error seen below:

cmu@cmu:/$ opam install bap-ida-python
The following actions will be performed:
  ∗  install conf-ida             0.1         [required by bap-ida-python]
  ∗  install uuidm                0.9.6       [required by bap-std, bap-traces]
  ∗  install bap-std              1.1.0       [required by bap]
  ∗  install bap-warn-unused      1.1.0       [required by bap]
  ∗  install bap-traces           1.1.0       [required by bap]
  ∗  install bap-term-mapper      1.1.0       [required by bap]
  ∗  install bap-taint            1.1.0       [required by bap]
  ∗  install bap-symbol-reader    1.1.0       [required by bap]
  ∗  install bap-objdump          1.1.0       [required by bap]
  ∗  install bap-microx           1.1.0       [required by bap]
  ∗  install bap-mc               1.1.0       [required by bap]
  ∗  install bap-llvm             1.1.0       [required by bap]
  ∗  install bap-frontend         1.1.0       [required by bap]
  ∗  install bap-dump-symbols     1.1.0       [required by bap]
  ∗  install bap-demangle         1.1.0       [required by bap]
  ∗  install bap-callsites        1.1.0       [required by bap]
  ∗  install bap-cache            1.1.0       [required by bap]
  ∗  install bap-byteweight       1.1.0       [required by bap]
  ∗  install bap-api              1.1.0       [required by bap]
  ∗  install bap-abi              1.1.0       [required by bap]
  ∗  install bap-trace            1.1.0       [required by bap]
  ∗  install bap-taint-propagator 1.1.0       [required by bap]
  ∗  install bap-print            1.1.0       [required by bap]
  ∗  install bap-c                1.1.0       [required by bap]
  ∗  install bap-x86              1.1.0       [required by bap]
  ∗  install bap-frontc           1.1.0       [required by bap]
  ∗  install bap-arm              1.1.0       [required by bap]
  ∗  install bap                  1.1.0       [required by bap-ida-python]
  ∗  install bap-ida-python       1.2.0
===== ∗  29 =====
Do you want to continue ? [Y/n] Y

=-=- Gathering sources =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[bap-api.1.1.0] https://github.com/BinaryAnalysisPlatform/bap/archive/v1.1.0.tar.gz downloaded
[bap.1.1.0] https://github.com/BinaryAnalysisPlatform/bap/archive/v1.1.0.tar.gz downloaded
[bap-abi.1.1.0] https://github.com/BinaryAnalysisPlatform/bap/archive/v1.1.0.tar.gz downloaded
[bap-arm.1.1.0] https://github.com/BinaryAnalysisPlatform/bap/archive/v1.1.0.tar.gz downloaded
[bap-byteweight.1.1.0] https://github.com/BinaryAnalysisPlatform/bap/archive/v1.1.0.tar.gz downloaded
[bap-c.1.1.0] https://github.com/BinaryAnalysisPlatform/bap/archive/v1.1.0.tar.gz downloaded
[bap-callsites.1.1.0] https://github.com/BinaryAnalysisPlatform/bap/archive/v1.1.0.tar.gz downloaded
[bap-cache.1.1.0] https://github.com/BinaryAnalysisPlatform/bap/archive/v1.1.0.tar.gz downloaded
[bap-demangle.1.1.0] https://github.com/BinaryAnalysisPlatform/bap/archive/v1.1.0.tar.gz downloaded
[bap-frontend.1.1.0] https://github.com/BinaryAnalysisPlatform/bap/archive/v1.1.0.tar.gz downloaded
[bap-frontc.1.1.0] https://github.com/BinaryAnalysisPlatform/bap/archive/v1.1.0.tar.gz downloaded
[bap-dump-symbols.1.1.0] https://github.com/BinaryAnalysisPlatform/bap/archive/v1.1.0.tar.gz downloaded
[bap-llvm.1.1.0] https://github.com/BinaryAnalysisPlatform/bap/archive/v1.1.0.tar.gz downloaded
[bap-ida-python.1.2.0] https://github.com/BinaryAnalysisPlatform/bap-ida-python/archive/v1.2.0.tar.gz downloaded
[bap-microx.1.1.0] https://github.com/BinaryAnalysisPlatform/bap/archive/v1.1.0.tar.gz downloaded
[bap-mc.1.1.0] https://github.com/BinaryAnalysisPlatform/bap/archive/v1.1.0.tar.gz downloaded
[bap-print.1.1.0] https://github.com/BinaryAnalysisPlatform/bap/archive/v1.1.0.tar.gz downloaded
[bap-std.1.1.0] https://github.com/BinaryAnalysisPlatform/bap/archive/v1.1.0.tar.gz downloaded
[bap-objdump.1.1.0] https://github.com/BinaryAnalysisPlatform/bap/archive/v1.1.0.tar.gz downloaded
[bap-symbol-reader.1.1.0] https://github.com/BinaryAnalysisPlatform/bap/archive/v1.1.0.tar.gz downloaded
[bap-taint.1.1.0] https://github.com/BinaryAnalysisPlatform/bap/archive/v1.1.0.tar.gz downloaded
[bap-taint-propagator.1.1.0] https://github.com/BinaryAnalysisPlatform/bap/archive/v1.1.0.tar.gz downloaded
[bap-term-mapper.1.1.0] https://github.com/BinaryAnalysisPlatform/bap/archive/v1.1.0.tar.gz downloaded
[bap-trace.1.1.0] https://github.com/BinaryAnalysisPlatform/bap/archive/v1.1.0.tar.gz downloaded
[bap-traces.1.1.0] https://github.com/BinaryAnalysisPlatform/bap/archive/v1.1.0.tar.gz downloaded
[bap-warn-unused.1.1.0] https://github.com/BinaryAnalysisPlatform/bap/archive/v1.1.0.tar.gz downloaded
[uuidm.0.9.6] http://erratique.ch/software/uuidm/releases/uuidm-0.9.6.tbz downloaded
[bap-x86.1.1.0] https://github.com/BinaryAnalysisPlatform/bap/archive/v1.1.0.tar.gz downloaded

=-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
∗  installed conf-ida.0.1
[ERROR] The compilation of uuidm failed at "ocaml pkg/pkg.ml build --pinned false --with-cmdliner true".

#=== ERROR while installing uuidm.0.9.6 =======================================#
# opam-version 1.2.2
# os           linux
# command      ocaml pkg/pkg.ml build --pinned false --with-cmdliner true
# path         /home/cmu/.opam/bap-0821/build/uuidm.0.9.6
# compiler     4.03.0
# exit-code    1
# env-file     /home/cmu/.opam/bap-0821/build/uuidm.0.9.6/uuidm-31386-ece7a3.env
# stdout-file  /home/cmu/.opam/bap-0821/build/uuidm.0.9.6/uuidm-31386-ece7a3.out
# stderr-file  /home/cmu/.opam/bap-0821/build/uuidm.0.9.6/uuidm-31386-ece7a3.err
### stdout ###
# [...]
# ocamlfind ocamlopt -shared -linkall -package bytes -I src src/uuidm.cmxa -o src/uuidm.cmxs
# ocamlfind ocamlc -c -g -bin-annot -safe-string -package bytes -I src -I test -o src/uuidm.cmo src/uuidm.ml
# ocamlfind ocamlc -a -package bytes -I src src/uuidm.cmo -o src/uuidm.cma
# ocamlfind ocamldep -package cmdliner -package bytes -modules test/uuidtrip.ml > test/uuidtrip.ml.depends
# ocamlfind ocamlc -c -g -bin-annot -safe-string -package cmdliner -package bytes -I test -I src -o test/uuidtrip.cmo test/uuidtrip.ml
# + ocamlfind ocamlc -c -g -bin-annot -safe-string -package cmdliner -package bytes -I test -I src -o test/uuidtrip.cmo test/uuidtrip.ml
# File "test/uuidtrip.ml", line 85, characters 8-13:
# Error: Unbound value const
# Hint: Did you mean cosh or cos?
# Command exited with code 2.
### stderr ###
# pkg.ml: [ERROR] cmd ['ocamlbuild' '-use-ocamlfind' '-classic-display' '-tag' 'debug'
#      '-build-dir' '_build' 'opam' 'pkg/META' 'CHANGES.md' 'LICENSE.md'
#      'README.md' 'src/uuidm.a' 'src/uuidm.cmxs' 'src/uuidm.cmxa'
#      'src/uuidm.cma' 'src/uuidm.cmx' 'src/uuidm.cmi' 'src/uuidm.mli'
#      'test/uuidtrip.native']: exited with 10



=-=- Error report -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
The following actions were aborted
  ∗  install bap                  1.1.0
  ∗  install bap-abi              1.1.0
  ∗  install bap-api              1.1.0
  ∗  install bap-arm              1.1.0
  ∗  install bap-byteweight       1.1.0
  ∗  install bap-c                1.1.0
  ∗  install bap-cache            1.1.0
  ∗  install bap-callsites        1.1.0
  ∗  install bap-demangle         1.1.0
  ∗  install bap-dump-symbols     1.1.0
  ∗  install bap-frontc           1.1.0
  ∗  install bap-frontend         1.1.0
  ∗  install bap-ida-python       1.2.0
  ∗  install bap-llvm             1.1.0
  ∗  install bap-mc               1.1.0
  ∗  install bap-microx           1.1.0
  ∗  install bap-objdump          1.1.0
  ∗  install bap-print            1.1.0
  ∗  install bap-std              1.1.0
  ∗  install bap-symbol-reader    1.1.0
  ∗  install bap-taint            1.1.0
  ∗  install bap-taint-propagator 1.1.0
  ∗  install bap-term-mapper      1.1.0
  ∗  install bap-trace            1.1.0
  ∗  install bap-traces           1.1.0
  ∗  install bap-warn-unused      1.1.0
  ∗  install bap-x86              1.1.0
The following actions failed
  ∗  install uuidm 0.9.6
The following changes have been performed
  ∗  install conf-ida 0.1

The former state can be restored with:
    opam switch import "~/.opam/bap-0821/backup/state-20170814204005.export"

**Comment by ivg** [comment] 2017-09-14 21:39
It looks like that the opam solver managed to wander into some weird state, where an upstream package fails to compile. I will report this issue upstream, and we will resolve it separately. Please, before you will destroy this switch can you provide the following information:

1. Output of `opam config print`
2. Output of `opam show cmdliner` 
3. the file  "~/.opam/bap-0821/backup/state-20170814204005.export" (or if it no longer exists, then just generate a new one with `opam switch export failed.export` and upload the `failed.export` file, or just copy it here). 

This will help us with the upstream maintainers to figure out what has happened. 

After that I would suggest you, first of all, to make sure, that you have an external opam solver installed (in debian based systems the package is called `aspcud`). Then, make sure, that you opam state is up-to-date by issuing the `opam update` command. The next step, would be to create a fresh new compiler switch, install the latest bap. And then install `bap-ida-python`. Do not allow `opam` to downgrade bap. If it still tries to do this (maybe you have an old version of a solver or opam in your repository), the force it with explicit version annotations, e.g., `opam install bap.1.3.0 bap-ida-python`.

**Comment by ivg** [comment] 2017-09-14 21:54
@dbuenzli, would you like me to create an issue in the opam-repository?

P.S. this is kind of weird issue, on a first glance it strange as uuidm can't find the `const` function, that was added in 0.9.8, so it means that the installed version of cmdliner is 0.9.7 or lower. However, the uuidm package spec contains the conflict statement that prevents too old cmdliner from installing. Looks like an opam bug...

**Comment by dbuenzli** [comment] 2017-09-14 23:47
> Output of opam config print

It's `opam config report`.

> Looks like an opam bug...

Indeed, so the issue should rather go in `opam` but the above info is needed.

**Comment by Dinatrix** [comment] 2017-09-15 14:31
Here were the outputs from those commands (Though only the second appeared to complete successfully):

cmu@cmu:/$ opam config print
opam: COMMAND argument: invalid value `print', expected one of
      `pef-universe', `cudf-universe', `report', `subst', `list', `var',
      `exec', `setup' or `env'
Usage: opam config [OPTION]... [COMMAND] [ARG]...
Try `opam config --help' or `opam --help' for more information.
cmu@cmu:/$ opam show cmdliner
             package: cmdliner
             version: 0.9.7
          repository: bap
        upstream-url: http://erratique.ch/software/cmdliner/releases/cmdliner-0.9.7.tbz
       upstream-kind: http
   upstream-checksum: 46d7553b95f623f811df2a844fb448fb
            homepage: http://erratique.ch/software/cmdliner
         bug-reports: https://github.com/dbuenzli/cmdliner/issues
            dev-repo: http://erratique.ch/repos/cmdliner.git
              author: Daniel Bünzli <daniel.buenzli i@erratique.ch>
             license: BSD3
                 doc: http://erratique.ch/software/cmdliner/doc/Cmdliner
                tags: cli, system, declarative, org:erratique
             depends: ocamlbuild
  installed-versions: 0.9.6 [fresh-bap], 0.9.7 [bap-0821]
  available-versions: 0.9.2, 0.9.4, 0.9.5, 0.9.6, 0.9.7, 0.9.8, 1.0.0, 1.0.1, 1.0.2
         description: Declarative definition of command line interfaces for OCaml

Cmdliner is a module for the declarative definition of command line
interfaces.

It provides a simple and compositional mechanism to convert command
line arguments to OCaml values and pass them to your functions. The
module automatically handles syntax errors, help messages and UNIX man
page generation. It supports programs with single or multiple commands
and respects most of the [POSIX][1] and [GNU][2] conventions.

Cmdliner is made of a single independent module and distributed under
the BSD3 license.

[1]: http://pubs.opengroup.org/onlinepubs/009695399/basedefs/xbd_chap12.html
[2]: http://www.gnu.org/software/libc/manual/html_node/Argument-Syntax.html

cmu@cmu:/$ opam switch export failed.export
Fatal error:
OpamSystem.File_not_found("/failed.export")

I was unable to find the file you noted on the system ("~/.opam/bap-0821/backup/state-20170814204005.export") but did not change the switch since the previous install attempt.

**Comment by ivg** [comment] 2017-09-15 14:37
1. it should be `opam config report` sorry
3. you should change to a directory where you have a permission to create files, e.g.,
```
cd $HOME; opam switch export failed.export
```

Then you will find the `failed.export` file in your home folder.

**Comment by Dinatrix** [comment] 2017-09-15 19:16
cmu@cmu:/$ opam config report
# OPAM config report
# opam-version    1.2.2 
# self-upgrade    no
# os              linux
# external-solver no
# criteria        -removed,-notuptodate,-changed
# jobs            4
# repositories    1* (http), 1 (version-controlled)
# pinned          0
# current-switch  bap-0821
# last-update     2017-08-29 16:54

The failed.export:

ocamlbuild	0.11.0	installed
ocamlfind	1.7.3	installed
ocamlgraph	1.8.7	installed
ocamlify	0.0.1	installed
ocamlmod	0.0.8	installed
ppx_assert	113.33.00	installed
ppx_bench	113.33.00+4.03	installed
ppx_bin_prot	113.33.00+4.03	installed
ppx_compare	113.33.00+4.03	installed
ppx_core	113.33.01+4.03	installed
ppx_custom_printf	113.33.00+4.03	installed
ppx_deriving	4.1	installed
ppx_driver	113.33.02+4.03	installed
ppx_enumerate	113.33.00+4.03	installed
ppx_expect	113.33.01+4.03	installed
ppx_fail	113.33.00+4.03	installed
ppx_fields_conv	113.33.00+4.03	installed
ppx_here	113.33.00	installed
ppx_inline_test	113.33.00+4.03	installed
ppx_jane	113.33.00	installed
ppx_let	113.33.00+4.03	installed
ppx_optcomp	113.33.00+4.03	installed
ppx_pipebang	113.33.00+4.03	installed
ppx_sexp_conv	113.33.01+4.03	installed
ppx_sexp_message	113.33.00+4.03	installed
ppx_sexp_value	113.33.00+4.03	installed
ppx_tools	5.0+4.03.0	installed
ppx_type_conv	113.33.02+4.03	installed
ppx_typerep_conv	113.33.00+4.03	installed
ppx_variants_conv	113.33.00+4.03	installed
re	1.7.1	installed
react	1.2.1	installed
regular	1.2.0	installed
result	1.2	installed
sexplib	113.33.00+4.03	installed
stringext	1.5.0	installed
text-tags	1.2.0	installed
topkg	0.9.0	installed
typerep	113.24.00	installed
uri	1.9.2	installed
utop	2.0.1	installed
uuidm	0.9.5	root
variantslib	113.24.00	installed
zarith	1.5	installed
zed	1.5	installed

**Comment by ivg** [comment] 2017-09-15 20:32
Aha, now I'm suspecting that I know what happend, can you please show the output of the `opam remote` command?

**Comment by Dinatrix** [comment] 2017-09-15 20:39
cmu@cmu:~$ opam remote
  10 [git]          bap     git://github.com/BinaryAnalysisPlatform/opam-repository
   0 [http]     default     https://opam.ocaml.org

**Comment by ivg** [comment] 2017-09-18 11:01
So, it looks like that the `bap` repo wasn't up to date. I've pulled the latest changes into it from the upstream. Make sure that you update your opam state with `opam update`. Then I would suggest you to install bap from scratch.

**Comment by Dinatrix** [comment] 2017-09-18 16:00
After updating opam, I ran into a problem during the bap install:

#=== ERROR while installing bap-std.1.3.0 =====================================#
# opam-version 1.2.2
# os           linux
# command      make
# path         /home/cmu/.opam/bap-0821/build/bap-std.1.3.0
# compiler     4.03.0
# exit-code    2
# env-file     /home/cmu/.opam/bap-0821/build/bap-std.1.3.0/bap-std-32285-7afd23.env
# stdout-file  /home/cmu/.opam/bap-0821/build/bap-std.1.3.0/bap-std-32285-7afd23.out
# stderr-file  /home/cmu/.opam/bap-0821/build/bap-std.1.3.0/bap-std-32285-7afd23.err
### stdout ###
# [...]
# /home/cmu/.opam/bap-0821/bin/ocamlfind ocamlc -c -g -annot -bin-annot -short-paths -I lib/bap_config -I lib/bap_types -I lib/bap_image -I lib/bap_disasm -I lib/bap_sema -I lib/bap_bundle -I lib/bap_plugins -I lib/bap -pp 'ppx-jane -dump-ast -inline-test-lib bap' -predicates ppx_driver -package ppx_jane -package fileutils -package core_kernel -package uri -package unix -package camlzip -package findlib -package compiler-libs -package zarith -package uuidm -package regular -package ppx_variants_conv -package ppx_here -package ppx_enumerate -package ogre -package ocamlgraph -package monads -package graphlib -package dynlink -package compiler-libs.common -package cmdliner -package bap-future -I lib/bap -I lib/bap_config -I lib/bap_disasm -I lib/bap_image -I lib/bap_plugins -I lib/bap_sema -I lib/bap_types -o lib/bap/bap_event.cmo lib/bap/bap_event.ml
# /home/cmu/.opam/bap-0821/bin/ocamlfind ocamlc -c -g -annot -bin-annot -short-paths -I lib/bap_config -I lib/bap_types -I lib/bap_image -I lib/bap_disasm -I lib/bap_sema -I lib/bap_bundle -I lib/bap_plugins -I lib/bap -pp 'ppx-jane -dump-ast -inline-test-lib bap' -predicates ppx_driver -package ppx_jane -package fileutils -package core_kernel -package uri -package unix -package camlzip -package findlib -package compiler-libs -package zarith -package uuidm -package regular -package ppx_variants_conv -package ppx_here -package ppx_enumerate -package ogre -package ocamlgraph -package monads -package graphlib -package dynlink -package compiler-libs.common -package cmdliner -package bap-future -I lib/bap -I lib/bap_config -I lib/bap_disasm -I lib/bap_image -I lib/bap_plugins -I lib/bap_sema -I lib/bap_types -o lib/bap/bap_log.cmo lib/bap/bap_log.ml
# /home/cmu/.opam/bap-0821/bin/ocamlfind ocamlc -c -g -annot -bin-annot -short-paths -I lib/bap_config -I lib/bap_types -I lib/bap_image -I lib/bap_disasm -I lib/bap_sema -I lib/bap_bundle -I lib/bap_plugins -I lib/bap -pp 'ppx-jane -dump-ast -inline-test-lib bap' -predicates ppx_driver -package ppx_jane -package fileutils -package core_kernel -package uri -package unix -package camlzip -package findlib -package compiler-libs -package zarith -package uuidm -package regular -package ppx_variants_conv -package ppx_here -package ppx_enumerate -package ogre -package ocamlgraph -package monads -package graphlib -package dynlink -package compiler-libs.common -package cmdliner -package bap-future -I lib/bap -I lib/bap_config -I lib/bap_disasm -I lib/bap_image -I lib/bap_plugins -I lib/bap_sema -I lib/bap_types -o lib/bap/bap_project.cmo lib/bap/bap_project.ml
# /home/cmu/.opam/bap-0821/bin/ocamlfind ocamlc -c -g -annot -bin-annot -short-paths -I lib/bap_config -I lib/bap_types -I lib/bap_image -I lib/bap_disasm -I lib/bap_sema -I lib/bap_bundle -I lib/bap_plugins -I lib/bap -pp 'ppx-jane -dump-ast -inline-test-lib bap' -predicates ppx_driver -package ppx_jane -package fileutils -package core_kernel -package uri -package unix -package camlzip -package findlib -package compiler-libs -package zarith -package uuidm -package regular -package ppx_variants_conv -package ppx_here -package ppx_enumerate -package ogre -package ocamlgraph -package monads -package graphlib -package dynlink -package compiler-libs.common -package cmdliner -package bap-future -I lib/bap -I lib/bap_config -I lib/bap_disasm -I lib/bap_image -I lib/bap_plugins -I lib/bap_sema -I lib/bap_types -o lib/bap/bap_self.cmo lib/bap/bap_self.ml
# + /home/cmu/.opam/bap-0821/bin/ocamlfind ocamlc -c -g -annot -bin-annot -short-paths -I lib/bap_config -I lib/bap_types -I lib/bap_image -I lib/bap_disasm -I lib/bap_sema -I lib/bap_bundle -I lib/bap_plugins -I lib/bap -pp 'ppx-jane -dump-ast -inline-test-lib bap' -predicates ppx_driver -package ppx_jane -package fileutils -package core_kernel -package uri -package unix -package camlzip -package findlib -package compiler-libs -package zarith -package uuidm -package regular -package ppx_variants_conv -package ppx_here -package ppx_enumerate -package ogre -package ocamlgraph -package monads -package graphlib -package dynlink -package compiler-libs.common -package cmdliner -package bap-future -I lib/bap -I lib/bap_config -I lib/bap_disasm -I lib/bap_image -I lib/bap_plugins -I lib/bap_sema -I lib/bap_types -o lib/bap/bap_self.cmo lib/bap/bap_self.ml
# File "lib/bap/bap_self.ml", line 198, characters 20-75:
# Error: This expression has type 'a -> 'b -> unit -> unit
#        but an expression was expected of type ('c -> 'd) t
# Command exited with code 2.
# Makefile:8: recipe for target 'build' failed
### stderr ###
# make: *** [build] Error 1

**Comment by ivg** [comment] 2017-09-18 16:11
Your installation is definitely broken, I don't know how you managed to end at this stage, it might be a bug in opam itself, but you have a version of cmdliner that is not compatible with BAP. So my suggestion is to install BAP from scratch, and by "from scratch" I mean by starting from a clean state. You may keep the `bap-0821` state and report bug to the upstream, if you're interested. 

Here is the recipe, that should work.

```
opam remove remove bap
opam update
opam switch clean-bap -A4.03.0
eval `opam config env`
opam install bap
```

**Closed** 2017-09-20 18:52 UTC
