### ISSUE TITLE
the Partition module does not have any constructors

### ISSUE THREAD

**Issue by codyroux** [BinaryAnalysisPlatform/bap#869] opened 2018-09-07 17:19 UTC
In https://github.com/BinaryAnalysisPlatform/bap/blob/5ddb832cc6c86447fb9558982d42dfb1168efae2/lib/graphlib/graphlib_graph.ml

There is a `Partition.create` function, but in the exported interface in https://github.com/BinaryAnalysisPlatform/bap/blob/5ddb832cc6c86447fb9558982d42dfb1168efae2/lib/graphlib/graphlib_graph.mli

There seems to be no convenient way to create an element of `'a partition`. Am I missing something? Otherwise it might be useful to make `Partition.create` public.

**Comment by ivg** [comment] 2018-09-07 17:26
The partition type was specifically made abstract and private to graphlib, so that only graphlib algorithms that perform partitioning could create them. The main purpose of the partition data structure was to deliver the results of partitioning in some abstract way, that we can easy change later. I don't really think that we need to expose the constructor, as it will leak a lot of implementation details, which will limit our freedom in the future.

Do you have any specific use cases why it is needed?

**Comment by codyroux** [comment] 2018-09-07 18:06
I'm trying to implement a bisimulation algorithm using the `Graph` data
structure. This involves creating new partitions and refining them. As far
as I can tell, only the `strong_components` function creates a partition.
How would one implement similar functionality from outside of the
`Graphlib_graph` module?

Also, feel free to tell me if this isn't the appropriate forum for these
kinds of questions.

**Comment by ivg** [comment] 2018-09-07 21:50
It's appropriate, but you can also use gitter for more live discussions.  

Did you consider extracting the partitioning information into your own data structure (possibly containing graphlibs partition inside)?

**Comment by codyroux** [comment] 2018-09-10 14:50
I have, and I will, but how would one create, say, the partition containing
all nodes of an arbitrary graph?

Of course I can create my own partition type, but I'd kind of like to
re-use the one in BAP, which at the moment seems to be only used to
represent the SCCs in a given graph.

**Comment by ivg** [comment] 2018-09-10 15:07
I will resist publishing the `create` function, since it leaks too much details through the abstraction. For example, what if a user will pass a hashtable to it, and the change the table later? Or what if the mapping passed to the create function is not a partitioning at all? So there are quite a few invariants that are preserved internally in the module between callers and callees, and making this function public would be unsafe. The whole purpose of creating an abstract type `'a partition` was to encode that this mapping is a partition, and use the type system to witness it. 

I will, however, warmly welcome PRs that will extend the Partition module (or the Graphlib interface) with safe constructors and functional mutators. For example, you can add another function to Graphlib that will create other partitions. 

With all that said, the partition representation was designed as a constant data structure, that wouldn't be updated. For example, given current representation it wouldn't be easy to change the partition. But again, if you find a representation that is safe and efficient and you think that it will work better than the current implementation, please don't hesitate to submit a PR.

**Comment by codyroux** [comment] 2018-09-10 15:29
Sounds great, I'll try to do this. Of course would only add public
functions that preserve the invariant (possibly modulo some assumptions
about an 'equiv' input function?).

**Comment by ivg** [comment] 2018-09-10 15:51
Not sure that I understand what do you mean by "assumptions about an 'equiv' input function", but we will discuss everything in the PR. You're welcome to create a PR of a work in progress, so that we will have some ground for discussion. 

Also, we care a lot about backward compatibility and bump major number of a library once a breaking change is made to its interface (aka semantic versioning), so it would be ideal if we can keep the interface. Basically it means, that you can add new functions to `Group`, `Equiv`, `Partition`, `Graphlib` or any other module, but not to module type. You can also add optional parameters to functions.

**Comment by ivg** [comment] 2019-02-01 12:44
fixed in #892

**Closed by ivg** 2019-02-01 12:44 UTC
