### ISSUE TITLE
BAP 1.3.0-pre (from the PR) segfaults when loading libr_anal.so (from radare2)

### ISSUE THREAD

**Issue by maurer** [BinaryAnalysisPlatform/bap#697] opened 2017-08-23 05:04 UTC
[libr_anal.so](https://data.maurer.codes/libr_anal.so) when loaded with no commands (e.g. `bap ./libr_anal.so`) yields a Segmentation Fault.

GDB reports:

```
[maurer@brionac:~/Development/r2_bin_samples]$ gdb `which bap`
GNU gdb (GDB) 7.12.1
Copyright (C) 2017 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /nix/store/00jv5fh9cymx2j3hj74lbbzhz83qgqp8-ocaml-bap-1.3-pre/bin/bap...done.
(gdb) run ./libr_anal.so 
Starting program: /nix/store/00jv5fh9cymx2j3hj74lbbzhz83qgqp8-ocaml-bap-1.3-pre/bin/bap ./libr_anal.so
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/nix/store/kjwbqnh13dxh6w4pk2gb3ddmhpiaihqg-glibc-2.25/lib/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
0x0000000000cc2349 in camlList__rev_append_1029 ()
(gdb) bt full
BFD: reopening /tmp/bap_abie72caf.cmxs: No such file or directory

BFD: reopening /tmp/bap_abie72caf.cmxs: No such file or directory

Python Exception <class 'gdb.error'> Can't read data for section '.eh_frame' in file '/tmp/bap_abie72caf.cmxs': 
#0  0x0000000000cc2349 in camlList__rev_append_1029 ()
No symbol table info available.
(gdb) 
```

However, I've received different locations different times, including in a `cons` function and inside the GC, causing me to suspect backtraces are not going to be helpful, and general corruption is occurring somehow.

This file loaded correctly in 1.2.

**Comment by maurer** [comment] 2017-08-23 05:05
As an additional note, this will occur even with just an attempt to create an `Image` out of this file - I originally discovered the bug when trying to call it from my stuff - so that restricts the area that could be causing the corruption.

**Comment by ivg** [comment] 2017-08-23 12:22
Wow! thanks, this was the last minute catch, I was going to merge it yesterday evening. We will investigate. Meantime, can you tell which version of LLVM did you use?

**Comment by ivg** [comment] 2017-08-23 12:49
So, I can't reproduce it on my tip of the branch, so it might because either

1) it is llvm-3.8 specific (I'm currently rebuilding with 3.8 to check this hypothesis)
2) it was fixed yesterday before you pulled this branch.

**Comment by ivg** [comment] 2017-08-23 13:03
So, with 3.8 and 4.0 all works fine. The a93d7d7 commit shouldn't actually affect this file, as it is ARM specific. So my conclusion is that we can't actually reproduce the issue. So, can you tell us:

1) which commit did you use?
2) which compiler version?
3) which version of llvm?
4) gcc version?
5) which CPU are you using?

Concerning the CPU, there is a [hardware bug][1] in Intel Skylake / Kaby Lake, so check whether you have one of the offending CPU models.

[1]: https://lists.debian.org/debian-devel/2017/06/msg00308.html

**Comment by maurer** [comment] 2017-08-23 13:12
1. I as using commit f296ce4f689b8fdf76b2512d5651ae2d9d3edbc8
2. OCaml 4.02.3 (Meant to upgrade to 4.03, but looking at my logs I didn't)
3. LLVM 3.8
4. GCC 6.4
5. It is a skylake CPU (i7-6700k)

**Comment by maurer** [comment] 2017-08-23 13:17
P.S. - I have Skylake on my destkop, and Kaby Lake on my laptop, so evidently I have zero unaffected CPUs.

**Comment by ivg** [comment] 2017-08-23 13:20
Yeah, so it is the skylake bug, Oleg also has the same CPU, and experienced the same sporadic segfaults. Another argument for the skylake bug is that the segfault occurs inside the OCaml code, not inside the llvm. 

Fixes for both CPU available (see the link above). Skylake is easy fixable, the last time I checked Kaby Lake was a little harder to fix, but still doable.

**Comment by ivg** [comment] 2017-08-23 15:11
After a couple of hours of trying we were able to reproduce the issue on Oleg's Skylake (several times, usually failing somewhere in the GC, and once failed with an illegal instruction, that proves that the problem is in a CPU). Moreover, the failures were observed on the old version, not the PR one. On mine older CPU I don't see any segfaults or other problems during this period of time. 

I think that we have evidence beyond the reasonable doubt, that this is a CPU issue, so I'm closing this.

**Closed by ivg** 2017-08-23 15:11 UTC

**Comment by maurer** [comment] 2017-08-23 16:26
I can confirm that after updating my laptop's microcode, the bug has ceased to reproduce here at least.
