### ISSUE TITLE
High memory usage on some binaries

### ISSUE THREAD

**Issue by jlacomis** [BinaryAnalysisPlatform/bap#936] opened 2019-03-27 19:23 UTC
I am running a tool on that invokes bap on thousands of binaries that I have collected and on occasional binaries the memory usage is incredibly high (I managed to use all 128GB of RAM on the server I'm running on). I was able to narrow down one of these binaries and replicate the problem locally.

Replication:
- Clone and build this repository (with `make`): https://github.com/michaeldubyu/HallamSSW
- run `bap ssw.o --pass=loc --symbolizer=objdump --rooter=internal`

Symptoms:
- Uses all memory I've been able to test it with (at least 32GB).

I'm also attaching the binary that I compiled on my machine (64-bit Fedora 27, kernel 4.18.16-100,  Red Hat GCC 7.3.1-6) in case it can't be replicated with a locally-compiled binary.

Binary:
[ssw.o.zip](https://github.com/BinaryAnalysisPlatform/bap/files/3014944/ssw.o.zip)

**Comment by ivg** [comment] 2019-03-27 19:29
The problem is in your pass `loc`, it has nothing to do with bap

```
$ /usr/bin/time -v bap ssw.o
        Command being timed: "bap ssw.o"
        User time (seconds): 2.17
        System time (seconds): 0.16
        Percent of CPU this job got: 99%
        Elapsed (wall clock) time (h:mm:ss or m:ss): 0:02.34
        Average shared text size (kbytes): 0
        Average unshared data size (kbytes): 0
        Average stack size (kbytes): 0
        Average total size (kbytes): 0
        Maximum resident set size (kbytes): 185372
        Average resident set size (kbytes): 0
        Major (requiring I/O) page faults: 23
        Minor (reclaiming a frame) page faults: 24571
        Voluntary context switches: 2
        Involuntary context switches: 9
        Swaps: 0
        File system inputs: 0
        File system outputs: 153344
        Socket messages sent: 0
        Socket messages received: 0
        Signals delivered: 0
        Page size (bytes): 4096
        Exit status: 0
```

**Comment by jlacomis** [comment] 2019-03-28 14:30
This is strange, I suspected that it might be a plugin written by the authors of the tool I'm using, so I installed bap locally using `opam` and ran that command. Without the compiled pass I expect that the command would fail, but it didn't. Does it run the rooter and symbolizer before trying to run the pass?

To test it again, I just eliminated the pass and tried to dump the program:
`bap -d --symbolizer=objdump --rooter=internal ssw.o`
This also used 32GB of memory usage before I had to kill it.

(in case you're curious, the `loc` plugin the tool is trying to run is [here](https://github.com/eth-sri/debin/blob/master/ocaml/loc.ml))

**Comment by ivg** [comment] 2019-03-28 14:38
> Does it run the rooter and symbolizer before trying to run the pass?

Yes, symbolizers and rooters are use to reconstruct the program CFG, so they are run during the program reconstruction phase. Passes are applied in order to the reconstructed program and therefore are run after. Didn't look yet at the `loc` pass, but without it I can't reproduce it, e.g.,

```
$ /usr/bin/time -v bap -d --symbolizer=objdump --rooter=internal ssw.o | wc --lines
        Command being timed: "bap -d --symbolizer=objdump --rooter=internal ssw.o"
        User time (seconds): 1.80
        System time (seconds): 0.20
        Percent of CPU this job got: 99%
        Elapsed (wall clock) time (h:mm:ss or m:ss): 0:02.00
        Average shared text size (kbytes): 0
        Average unshared data size (kbytes): 0
        Average stack size (kbytes): 0
        Average total size (kbytes): 0
        Maximum resident set size (kbytes): 144604
        Average resident set size (kbytes): 0
        Major (requiring I/O) page faults: 77
        Minor (reclaiming a frame) page faults: 28504
        Voluntary context switches: 19
        Involuntary context switches: 7
        Swaps: 0
        File system inputs: 0
        File system outputs: 198912
        Socket messages sent: 0
        Socket messages received: 0
        Signals delivered: 0
        Page size (bytes): 4096
        Exit status: 0
11016
```
where
```
$ bap --version
1.5.0
```

Compiled purely from the opam release. 

So what is your setup? Are you using Docker, btw?

**Comment by jlacomis** [comment] 2019-03-28 14:47
Apologies, I should know enough about debugging to minimize the problem first. Here's what I get for `bap ssw.o` (I ended up killing it before my system became unresponsive):

```
$ /usr/bin/time -v bap ssw.o
^CCommand exited with non-zero status 250
	Command being timed: "bap ssw.o"
	User time (seconds): 504.56
	System time (seconds): 7.81
	Percent of CPU this job got: 99%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 8:33.84
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 19597472
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 0
	Minor (reclaiming a frame) page faults: 6417200
	Voluntary context switches: 27
	Involuntary context switches: 5456
	Swaps: 0
	File system inputs: 0
	File system outputs: 384
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 250
```
I installed it on an opam switch using the 4.05.0 compiler, and `opam depext --install bap` and get:
```
$ bap --version
1.4.0
```
I'm running a pretty stock Fedora 27 release on bare metal, although the tool I'm having the same problem with is running in Docker.

**Comment by jlacomis** [comment] 2019-03-28 14:53
I also just tried it on another machine running Ubuntu 16.04.5 LTS by installing from scratch on an opam 4.05.0 switch and it worked as expected (i.e., ran quickly and didn't use all the memory). I followed all the same steps, but it appears that the version of bap installed on that machine is 1.5.0, while my local machine installed 1.4.0. On my local machine (the broken one), `opam --version` gives me `2.0.0~beta6`, while on the Ubuntu machine (the working one), `opam --version` gives me `2.0.0~rc`.

**Comment by ivg** [comment] 2019-03-28 15:04
Ah, so it is BAP 1.4.0, then it makes sense. There were problems with some x86 instructions which were exploding the state during normalization. Should be fixed in 1.5.0.

**Comment by ivg** [comment] 2019-03-28 16:06
I think we can close it now :)

**Comment by jlacomis** [comment] 2019-03-28 16:06
Thanks, I'll close this issue. Do you happen to know why opam might install an old version of BAP?

**Closed by ivg** 2019-03-28 16:06 UTC

**Comment by ivg** [comment] 2019-03-28 16:14
Several possible reasons:
1) the `opam update` command wasn't run for many months
2) bap was installed using opam 1.x and then opam was updated. bap 1.4.0 is the latest version that you can install with opam 1.x
3) bap was pinned for some reason 
4) you're using alpha version of opam, which may be just broken. Consider updating to the latest stable version.
